name: Build SPK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: 'Checkout build scripts'
        with:
          repository: 'SynologyOpenSource/pkgscripts-ng'
          ref: 'DSM7.0'
          path: 'build/pkgscripts-ng'

      - uses: actions/checkout@v2
        with:
          path: 'build/pkgscripts-ng/source/Duplicati'

      - name: Deploy build environment
        run: sudo ./EnvDeploy -v 7.0 -p armada38x
        working-directory: 'build/pkgscripts-ng'

      - name: Build
        run: sudo ./PkgCreate.py -v 7.0 -p armada38x Duplicati
        working-directory: 'build/pkgscripts-ng'

      - uses: actions/upload-artifact@v2
        with:
          name: Duplicati
          path: build_env/ds.armada38x-7.0/image/packages