name: Build SPK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ZIP_URL: 'https://updates.duplicati.com/beta/duplicati-2.0.6.3_beta_2021-06-17.zip'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: 'Checkout build scripts'
        with:
          repository: 'SynologyOpenSource/pkgscripts-ng'
          ref: 'DSM7.0'
          path: 'build/pkgscripts-ng'

      - uses: actions/checkout@v2
        with:
          path: 'build/source/Duplicati'

      - name: Run build script
        run: 'python3 build_scripts/build.py'
        working-directory: 'build/source/Duplicati'

      - name: Cache toolkit tarballs
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: 'build/toolkit_tarballs'
          key: tarballs-${{ hashFiles('build/toolkit_tarballs/*.txz') }}
          restore-keys: |
            tarballs-

      - name: Get CA certificates
        run: wget https://curl.se/ca/cacert.pem
        working-directory: 'build/source/Duplicati/build_scripts'

      - name: Download zip
        run: wget --no-verbose -O duplicati.zip $ZIP_URL
        working-directory: 'build/source/Duplicati'

      - name: Deploy build environment
        run: sudo ./EnvDeploy -v 7.0 -p armada38x
        working-directory: 'build/pkgscripts-ng'

      - name: Build
        run: sudo ./PkgCreate.py -v 7.0 -p armada38x Duplicati
        working-directory: 'build/pkgscripts-ng'

      - uses: actions/upload-artifact@v2
        with:
          name: Duplicati
          path: 'build/build_env/ds.armada38x-7.0/image/packages'